services:
  - type: web
    name: echowave
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn MusicPlayer.wsgi --preload --workers=2 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DJANGO_SETTINGS_MODULE
        value: MusicPlayer.settings
      - key: DEBUG
        value: "False"
    autoDeploy: true
